Repository gsg-K1-FC/Ecommerce-App-team2, pull requests merged in 2020-11, with the labels that each got.

#1 Added file structure
  Assets/css/javaScript/script.js
  Assets/css/style.css
  index.html
Labels: in-progress

#22 Updated readme
  README.md
Labels: approved

#27 customer view
  assets/css/main.css
  assets/css/media.css
  assets/images/coot.jpg
  assets/images/cover .png
  assets/images/cover.jpg
  assets/images/cover1.jpg
  assets/images/cover2.jpg
  assets/images/cover3.jpg
  assets/images/images.jpg
  assets/images/lipstick.jpg
  assets/images/nike.jpg
  assets/images/palette.jpg
  assets/images/scarf.webp
  assets/js/cart.js
  assets/js/customer.js
  assets/js/main.js
  customer.html
  index.html
Labels: customer-feature, in-progress

#31 Make seller page.
  assets/css/main.css
  assets/js/customer.js
  assets/js/seller.js
  seller.html
Labels: approved
